fos_user_security:
    resource: "routing/security.yml"
    prefix: /

fos_user_profile:
    resource: "routing/profile.yml"
    prefix: /

fos_user_register:
    resource: "routing/registration.yml"
    prefix: /inscription

fos_user_resetting:
    resource: "routing/resetting.yml"
    prefix: /resetting

fos_user_change_password:
    resource: "routing/change_password.yml"
    prefix: /moncompte

fos_user_group:
    resource: "routing/group.yml"
    prefix: /groupe2
