parameters:
#    thiefaine_user.example.class: Thiefaine\UserBundle\Example

services:
#    thiefaine_user.example:
#        class: %thiefaine_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    thiefaine_user.profile.form.type:
        class: Thiefaine\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: thiefaine_user_profile }

    thiefaine_user.change_password.form.type:
        class: Thiefaine\UserBundle\Form\Type\ChangePasswordFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: thiefaine_user_change_password }