thiefaine_referentiel:
    resource: "@ThiefaineReferentielBundle/Resources/config/routing.yml"
    prefix:   /
    
thiefaine_referentiel_api:
    type: rest
    resource: "@ThiefaineReferentielBundle/Resources/config/routing_rest.yml"
    prefix: /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
    