fos_user_security_login:
  pattern: /
  defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
  pattern: /login_check
  defaults: { _controller: FOSUserBundle:Security:check }
  requirements: { _method: POST }

fos_user_security_logout:
  pattern: /deconnexion
  defaults: { _controller: FOSUserBundle:Security:logout }
