thiefaine_referentiel_api_alerte :
    type: rest
    resource: 'ThiefaineReferentielBundle:Alerte'
    name_prefix: thiefaine_referentiel_api_

thiefaine_referentiel_api_point :
    type: rest
    resource: 'ThiefaineReferentielBundle:Point'
    name_prefix: thiefaine_referentiel_api_

thiefaine_referentiel_api_utilisateurmobile :
    type: rest
    resource: 'ThiefaineReferentielBundle:Utilisateurmobile'
    name_prefix: thiefaine_referentiel_api_

thiefaine_referentiel_api_conseil :
    type: rest
    resource: 'ThiefaineReferentielBundle:Conseil'
    name_prefix: thiefaine_referentiel_api_