thiefaine_referentiel_api_point :
    type: rest
    resource: 'ThiefaineReferentielBundle:Point'
    name_prefix: thiefaine_referentiel_api_

thiefaine_referentiel_api_utilisateurmobile :
    type: rest
    resource: 'ThiefaineReferentielBundle:Utilisateurmobile'
    name_prefix: thiefaine_referentiel_api_

thiefaine_referentiel_api_Message :
    type: rest
    resource: 'ThiefaineReferentielBundle:Message
    name_prefix: thiefaine_referentiel_api_