#thiefaine_referentiel_homepage:
#    pattern:  /
#    defaults: { _controller: ThiefaineReferentielBundle:Default:index }

thiefaine_referentiel_accueil:
    pattern:  /accueil
    defaults: { _controller: ThiefaineReferentielBundle:Default:accueil }

thiefaine_referentiel_myaccount:
    pattern:  /myaccount
    defaults: { _controller: ThiefaineReferentielBundle:Default:myaccount }

thiefaine_referentiel_groupe:
    resource: "@ThiefaineReferentielBundle/Resources/config/routing/groupe.yml"
    prefix: /groupe

thiefaine_referentiel_zone:
    resource: "@ThiefaineReferentielBundle/Resources/config/routing/zone.yml"
    prefix: /zone

thiefaine_referentiel_point:
    resource: "@ThiefaineReferentielBundle/Resources/config/routing/point.yml"
    prefix:   /point

thiefaine_referentiel_user:
    resource: "@ThiefaineReferentielBundle/Resources/config/routing/utilisateurweb.yml"
    prefix: /utilisateurweb

thiefaine_conseil:
    resource: "@ThiefaineReferentielBundle/Resources/config/routing/conseil.yml"
    prefix:   /conseil

thiefaine_information:
    resource: "@ThiefaineReferentielBundle/Resources/config/routing/information.yml"
    prefix:   /information

thiefaine_alerte:
    resource: "@ThiefaineReferentielBundle/Resources/config/routing/alerte.yml"
    prefix:   /alerte

fos_user:
    resource: "@ThiefaineUserBundle/Resources/config/routing.yml"
    prefix: /
