#thiefaine_referentiel_homepage:
#    pattern:  /
#    defaults: { _controller: ThiefaineReferentielBundle:Default:index }


thiefaine_referentiel_accueil:
    pattern:  /accueil
    defaults: { _controller: ThiefaineReferentielBundle:Default:accueil }

thiefaine_referentiel_zone:
    resource: "routing/zone.yml"
    prefix: /zone

thiefaine_referentiel_point:
    resource: "routing/point.yml"
    prefix:   /point

thiefaine_referentiel_user:
    resource: "routing/utilisateurweb.yml"
    prefix: /utilisateur

thiefaine_conseil:
    resource: "routing/conseil.yml"
    prefix:   /conseil

thiefaine_information:
    resource: "routing/information.yml"
    prefix:   /information

thiefaine_categorie:
    resource: "routing/categorie.yml"
    prefix:   /categorie

thiefaine_referentiel_myaccount:
    pattern:  /myaccount
    defaults: { _controller: ThiefaineReferentielBundle:Default:myaccount }

fos_user:
    resource: "@ThiefaineUserBundle/Resources/config/routing.yml"
    prefix: /

thiefaine_utilisateurmobile:
    resource: "@ThiefaineReferentielBundle/Resources/config/routing/utilisateurmobile.yml"
    prefix:   /utilisateurmobile