services:
    thiefaine_user.group.form.type:
        class: Thiefaine\UserBundle\Form\Type\GroupFormType
        arguments: [%fos_user.model.group.class%]
        tags:
            - { name: form.type, alias: thiefaine_user_group }
