Alerte:
    type: entity
    table: ALERTE
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    oneToOne:
        message:
            targetEntity: Message
            inversedBy: alerte
            joinColumns:
                idmessage:
                    referencedColumnName: id
        zone:
            targetEntity: Zone
            inversedBy: alerte
            joinColumns:
                idzone:
                    referencedColumnName: id

    lifecycleCallbacks: {  }
