Gendarmerie:
    type: entity
    table: GENDARMERIE
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: false
            length: 255
            fixed: false
    oneToMany:
        groupes:
            targetEntity: Groupe
            mappedBy: gendarmerie

    lifecycleCallbacks: {  }
