Groupe:
    type: entity
    table: GROUPE
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        gerergroupes:
            type: boolean
            nullable: false
        gererutilisateurs:
            type: boolean
            nullable: false
        gereralertes:
            type: boolean
            nullable: false
        gererinfos:
            type: boolean
            nullable: false
        gererconseils:
            type: boolean
            nullable: false
    manyToOne:
        gendarmerie:
            targetEntity: Gendarmerie
            inversedBy: groupes
            joinColumns:
                idgendarmerie:
                    referencedColumnName: id
    oneToMany:
        utilisateursweb:
            targetEntity: Utilisateurweb
            mappedBy: groupe

    lifecycleCallbacks: {  }
