Point:
    type: entity
    table: POINT
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        latitude:
            type: string
            nullable: false
            length: 255
            fixed: false
        longitude:
            type: string
            nullable: false
            length: 255
            fixed: false
        radius:
            type: integer
            nullable: false
            unsigned: false
    manyToOne:
        zone:
            targetEntity: Zone
            inversedBy: points
            joinColumns:
                idzone:
                    referencedColumnName: id

    lifecycleCallbacks: {  }
