<?php

namespace Proxies\__CG__\Thiefaine\ReferentielBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Groupe extends \Thiefaine\ReferentielBundle\Entity\Groupe implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'id', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'nom', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gerergroupes', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gererutilisateurs', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gereralertes', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gererinfos', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gererconseils', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'idgendarmerie', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'utilisateursweb', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gendarmerie');
        }

        return array('__isInitialized__', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'id', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'nom', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gerergroupes', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gererutilisateurs', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gereralertes', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gererinfos', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gererconseils', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'idgendarmerie', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'utilisateursweb', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Groupe' . "\0" . 'gendarmerie');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Groupe $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setGerergroupes($gerergroupes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGerergroupes', array($gerergroupes));

        return parent::setGerergroupes($gerergroupes);
    }

    /**
     * {@inheritDoc}
     */
    public function getGerergroupes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGerergroupes', array());

        return parent::getGerergroupes();
    }

    /**
     * {@inheritDoc}
     */
    public function setGererutilisateurs($gererutilisateurs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGererutilisateurs', array($gererutilisateurs));

        return parent::setGererutilisateurs($gererutilisateurs);
    }

    /**
     * {@inheritDoc}
     */
    public function getGererutilisateurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGererutilisateurs', array());

        return parent::getGererutilisateurs();
    }

    /**
     * {@inheritDoc}
     */
    public function setGereralertes($gereralertes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGereralertes', array($gereralertes));

        return parent::setGereralertes($gereralertes);
    }

    /**
     * {@inheritDoc}
     */
    public function getGereralertes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGereralertes', array());

        return parent::getGereralertes();
    }

    /**
     * {@inheritDoc}
     */
    public function setGererinfos($gererinfos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGererinfos', array($gererinfos));

        return parent::setGererinfos($gererinfos);
    }

    /**
     * {@inheritDoc}
     */
    public function getGererinfos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGererinfos', array());

        return parent::getGererinfos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGererconseils($gererconseils)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGererconseils', array($gererconseils));

        return parent::setGererconseils($gererconseils);
    }

    /**
     * {@inheritDoc}
     */
    public function getGererconseils()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGererconseils', array());

        return parent::getGererconseils();
    }

    /**
     * {@inheritDoc}
     */
    public function addUtilisateursweb(\Thiefaine\ReferentielBundle\Entity\Utilisateurweb $utilisateursweb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUtilisateursweb', array($utilisateursweb));

        return parent::addUtilisateursweb($utilisateursweb);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUtilisateursweb(\Thiefaine\ReferentielBundle\Entity\Utilisateurweb $utilisateursweb)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUtilisateursweb', array($utilisateursweb));

        return parent::removeUtilisateursweb($utilisateursweb);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateursweb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateursweb', array());

        return parent::getUtilisateursweb();
    }

    /**
     * {@inheritDoc}
     */
    public function setGendarmerie(\Thiefaine\ReferentielBundle\Entity\Gendarmerie $gendarmerie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGendarmerie', array($gendarmerie));

        return parent::setGendarmerie($gendarmerie);
    }

    /**
     * {@inheritDoc}
     */
    public function getGendarmerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGendarmerie', array());

        return parent::getGendarmerie();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
