<?php

namespace Proxies\__CG__\Thiefaine\ReferentielBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Message extends \Thiefaine\ReferentielBundle\Entity\Message implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'titre', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'message', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'datecreation', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'datemiseajour', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'datevalidite', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'compteurlecture', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'urlphoto', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'urllien', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'idutilisateurweb', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'idtypemessage', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'alerte', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'typemessage', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'utilisateurweb');
        }

        return array('__isInitialized__', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'id', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'titre', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'message', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'datecreation', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'datemiseajour', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'datevalidite', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'compteurlecture', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'urlphoto', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'urllien', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'idutilisateurweb', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'idtypemessage', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'alerte', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'typemessage', '' . "\0" . 'Thiefaine\\ReferentielBundle\\Entity\\Message' . "\0" . 'utilisateurweb');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Message $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', array($titre));

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', array());

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', array($message));

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', array());

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatecreation($datecreation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatecreation', array($datecreation));

        return parent::setDatecreation($datecreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatecreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatecreation', array());

        return parent::getDatecreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemiseajour($datemiseajour)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemiseajour', array($datemiseajour));

        return parent::setDatemiseajour($datemiseajour);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemiseajour()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemiseajour', array());

        return parent::getDatemiseajour();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatevalidite($datevalidite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatevalidite', array($datevalidite));

        return parent::setDatevalidite($datevalidite);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatevalidite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatevalidite', array());

        return parent::getDatevalidite();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompteurlecture($compteurlecture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompteurlecture', array($compteurlecture));

        return parent::setCompteurlecture($compteurlecture);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompteurlecture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompteurlecture', array());

        return parent::getCompteurlecture();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlphoto($urlphoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlphoto', array($urlphoto));

        return parent::setUrlphoto($urlphoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlphoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlphoto', array());

        return parent::getUrlphoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrllien($urllien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrllien', array($urllien));

        return parent::setUrllien($urllien);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrllien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrllien', array());

        return parent::getUrllien();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlerte(\Thiefaine\ReferentielBundle\Entity\Alerte $alerte = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlerte', array($alerte));

        return parent::setAlerte($alerte);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlerte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlerte', array());

        return parent::getAlerte();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypemessage(\Thiefaine\ReferentielBundle\Entity\Typemessage $typemessage = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypemessage', array($typemessage));

        return parent::setTypemessage($typemessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypemessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypemessage', array());

        return parent::getTypemessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateurweb(\Thiefaine\ReferentielBundle\Entity\Utilisateurweb $utilisateurweb = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateurweb', array($utilisateurweb));

        return parent::setUtilisateurweb($utilisateurweb);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateurweb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateurweb', array());

        return parent::getUtilisateurweb();
    }

}
