conseil:
    pattern:  /
    defaults: { _controller: "ThiefaineReferentielBundle:Conseil:index" }

conseil_new:
    pattern:  /new
    defaults: { _controller: "ThiefaineReferentielBundle:Conseil:new" }

conseil_create:
    pattern:  /create
    defaults: { _controller: "ThiefaineReferentielBundle:Conseil:create" }
    requirements: { _method: post }

conseil_show:
    pattern:  /{id}/show
    defaults: { _controller: "ThiefaineReferentielBundle:Conseil:show" }

conseil_clone:
    pattern:  /{id}/clone
    defaults: { _controller: "ThiefaineReferentielBundle:Conseil:clone" }

conseil_cloneupdate:
    pattern:  /{id}/cloneupdate
    defaults: { _controller: "ThiefaineReferentielBundle:Conseil:cloneupdate" }

conseil_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ThiefaineReferentielBundle:Conseil:delete" }

