information:
    pattern:  /
    defaults: { _controller: "ThiefaineReferentielBundle:Information:index" }

information_new:
    pattern:  /new
    defaults: { _controller: "ThiefaineReferentielBundle:Information:new" }

information_create:
    pattern:  /create
    defaults: { _controller: "ThiefaineReferentielBundle:Information:create" }
    requirements: { _method: post }

information_show:
    pattern:  /{id}/show
    defaults: { _controller: "ThiefaineReferentielBundle:Information:show" }

information_clone:
    pattern:  /{id}/clone
    defaults: { _controller: "ThiefaineReferentielBundle:Information:clone" }

information_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ThiefaineReferentielBundle:Information:delete" }
