information:
    pattern:  /
    defaults: { _controller: "ThiefaineReferentielBundle:Information:index" }

information_show:
    pattern:  /{id}/show
    defaults: { _controller: "ThiefaineReferentielBundle:Information:show" }

information_new:
    pattern:  /new
    defaults: { _controller: "ThiefaineReferentielBundle:Information:new" }

information_create:
    pattern:  /create
    defaults: { _controller: "ThiefaineReferentielBundle:Information:create" }
    requirements: { _method: post }

information_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ThiefaineReferentielBundle:Information:edit" }

information_update:
    pattern:  /{id}/update
    defaults: { _controller: "ThiefaineReferentielBundle:Information:update" }
    requirements: { _method: post|put }

information_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ThiefaineReferentielBundle:Information:delete" }
    requirements: { _method: post|delete }
