utilisateurweb_list:
    pattern:  /
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:index" }

utilisateurweb_show:
    pattern:  /{id}/show
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:show" }

utilisateurweb_new:
    pattern:  /new
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:new" }

utilisateurweb_create:
    pattern:  /create
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:create" }
    requirements: { _method: post }

utilisateurweb_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:edit" }

utilisateurweb_update:
    pattern:  /{id}/update
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:update" }
    requirements: { _method: post|put }

utilisateurweb_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:delete" }
    requirements: { _method: post|delete }
