thiefaine_referentiel_utilisateurweb_list:
  pattern: /
  defaults: { _controller: ThiefaineReferentielBundle:Utilisateurweb:index }

utilisateurweb_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:edit" }

utilisateurweb_update:
    pattern:  /{id}/update
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:update" }
    requirements: { _method: post|put }

utilisateurweb_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ThiefaineReferentielBundle:Utilisateurweb:delete" }
    requirements: { _method: post|delete }
