Thiefaine\ReferentielBundle\Entity\Alerte:
    type: entity
    table: ALERTE
    indexes:
        ALERTE_MESSAGE_ID1:
            columns:
                - idmessage
        ALERTE_ZONE_ID1:
            columns:
                - idlieu
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idmessage:
            targetEntity: Message
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idmessage:
                    referencedColumnName: id
            orphanRemoval: false
        idlieu:
            targetEntity: Lieu
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idlieu:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
