Thiefaine\ReferentielBundle\Entity\Categorie:
    type: entity
    table: CATEGORIE
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: true
            length: 25
            fixed: false
    manyToMany:
        informations:
            targetEntity: Information
            mappedBy: categories
        conseils:
            targetEntity: Conseil
            mappedBy: categories

    lifecycleCallbacks: {  }
