Thiefaine\ReferentielBundle\Entity\Conseil:
    type: entity
    table: CONSEIL
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            fixed: false
        message:
            type: text
            nullable: false
            length: null
            fixed: false
        datecreation:
            type: datetime
            nullable: false
        datemiseajour:
            type: datetime
            nullable: true
        datevalidite:
            type: date
            nullable: true
        compteurlecture:
            type: integer
            nullable: true
            unsigned: false
        urlphoto:
            type: text
            nullable: true
            length: null
            fixed: false
        urllien:
            type: text
            nullable: true
            length: null
            fixed: false
    manyToOne:
        utilisateurweb:
            targetEntity: Thiefaine\UserBundle\Entity\Utilisateurweb
            inversedBy: conseils
            joinColumn:
                name: idutilisateurweb
                referencedColumnName: id

    lifecycleCallbacks: {  }
