Thiefaine\ReferentielBundle\Entity\Information:
    type: entity
    table: MESSAGE
    indexes:
        MESSAGE_TYPEMESSAGE_ID1:
            columns:
                - idtypemessage
        MESSAGE_UTILISATEURWEB_ID1:
            columns:
                - idutilisateur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        message:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        datecreation:
            type: datetime
            nullable: false
            comment: ''
        datemiseajour:
            type: datetime
            nullable: true
            comment: ''
        datevalidite:
            type: date
            nullable: true
            comment: ''
        compteurlecture:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        urlphoto:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        urllien:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    manyToOne:
        idtypemessage:
            targetEntity: Typemessage
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idtypemessage:
                    referencedColumnName: id
            orphanRemoval: false
        idutilisateur:
            targetEntity: Utilisateurweb
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
