Thiefaine\ReferentielBundle\Entity\Lieu:
    type: entity
    table: LIEU
    indexes:
        LIEU_UTILISATEURWEB_ID1:
            columns:
                - idutilisateurweb
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        latitude:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        longitude:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        zoom:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        actif:
            type: boolean
            nullable: false
            comment: ''
        datecreation:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: dateCreation
    manyToOne:
        idutilisateurweb:
            targetEntity: Utilisateurweb
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateurweb:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
