Thiefaine\ReferentielBundle\Entity\Message:
    type: entity
    table: MESSAGE
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            fixed: false
        message:
            type: text
            nullable: false
            length: null
            fixed: false
        datecreation:
            type: datetime
            nullable: false
        datemiseajour:
            type: datetime
            nullable: true
        datevalidite:
            type: date
            nullable: true
        compteurlecture:
            type: integer
            nullable: true
            unsigned: false
        urlphoto:
            type: text
            nullable: true
            length: null
            fixed: false
        urllien:
            type: text
            nullable: true
            length: null
            fixed: false
    manyToMany:
        categories:
            targetEntity: Categorie
            joinTable:
                name: CATEGORIE_MESSAGE
                joinColumns:
                    message:
                        referencedColumnName: id
                inverseJoinColumns:
                    categorie:
                        referencedColumnName: id
    manyToOne:
        typemessage:
            targetEntity: Typemessage
            inversedBy: messages
            joinColumns:
                idtypemessage:
                    referencedColumnName: id
        utilisateurweb:
            targetEntity: Thiefaine\UserBundle\Entity\Utilisateurweb
            inversedBy: messages
            joinColumn:
                name: idutilisateurweb
                referencedColumnName: id
    oneToOne:
        information:
            targetEntity: Information
            mappedBy: message

    lifecycleCallbacks: {  }
