Thiefaine\ReferentielBundle\Entity\Point:
    type: entity
    table: POINT
    indexes:
        POINT_ZONE1_ID1:
            columns:
                - idzone
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        latitude:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        longitude:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        radius:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
    manyToOne:
        idzone:
            targetEntity: Zone
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idzone:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
