Thiefaine\ReferentielBundle\Entity\Utilisateurweb:
    type: entity
    table: UTILISATEURWEB
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        prenom:
            type: string
            nullable: false
            length: 255
            fixed: false
        login:
            type: text
            nullable: false
            length: null
            fixed: false
        password:
            type: text
            nullable: false
            length: null
            fixed: false
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        infos:
            type: text
            nullable: true
            length: null
            fixed: false
    manyToOne:
        groupe:
            targetEntity: Groupe
            inversedBy: utilisateursweb
            joinColumns:
                idgroupe:
                    referencedColumnName: id
    oneToMany:
        messages:
            targetEntity: Message
            mappedBy: utilisateurweb
        zones:
            targetEntity: Zone
            mappedBy: utilisateurweb

    lifecycleCallbacks: {  }
