Thiefaine\ReferentielBundle\Entity\Zone:
    type: entity
    table: ZONE
    indexes:
        ZONE_UTILISATEURWEB_ID1:
            columns:
                - idutilisateur
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        latitude:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        longitude:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        zoom:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        actif:
            type: boolean
            nullable: false
            comment: ''
    manyToOne:
        idutilisateur:
            targetEntity: Utilisateurweb
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                idutilisateur:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
