Thiefaine\ReferentielBundle\Entity\Zone:
    type: entity
    table: ZONE
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        latitude:
            type: string
            nullable: true
            length: 255
            fixed: false
        longitude:
            type: string
            nullable: true
            length: 255
            fixed: false
        zoom:
            type: integer
            nullable: true
            unsigned: false
        actif:
            type: boolean
            nullable: true
    oneToMany:
        points:
            targetEntity: Point
            mappedBy: zone
        messages:
            targetEntity: Message
            mappedBy: zone
    manyToOne:
        utilisateurweb:
            targetEntity: Thiefaine\UserBundle\Entity\Utilisateurweb
            inversedBy: zones
            joinColumn:
                name: idutilisateurweb
                referencedColumnName: id

    lifecycleCallbacks: {  }
