Thiefaine\ReferentielBundle\Entity\Zone:
    type: entity
    table: ZONE
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        latitude:
            type: string
            nullable: false
            length: 255
            fixed: false
        longitude:
            type: string
            nullable: false
            length: 255
            fixed: false
        zoom:
            type: integer
            nullable: false
            unsigned: false
        actif:
            type: boolean
            nullable: false
    oneToMany:
        points:
            targetEntity: Point
            mappedBy: zone
        alertes:
            targetEntity: Alerte
            mappedBy: zone

    lifecycleCallbacks: {  }
